window.revelar = ScrollReveal({reset:true})

revelar.reveal('.hero-revel', {duration: 1500, distance: '90px', origin: 'bottom', interval: 200,delay:600})
revelar.reveal('.txt-revel', {duration: 1500, distance: '90px', origin: 'left', interval: 200})
revelar.reveal('.card', {duration: 1500, distance: '90px', origin: 'bottom', interval: 200})
revelar.reveal('.oc', {duration: 1500, distance: '90px', origin: 'bottom', interval: 200})
revelar.reveal('.tl', {duration: 1500, distance: '90px', origin: 'bottom', interval: 200})
revelar.reveal('.ws', {duration: 1500, distance: '80px', origin: 'bottom', interval: 200})
revelar.reveal('.card-revel', {duration: 1500, distance: '90px', origin: 'bottom', interval: 200, delay: 400})
revelar.reveal('.tc', {duration: 1500, distance: '90px', origin: 'bottom', interval: 200, delay: 500})